# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_admin(object):
    def setupUi(self, MainWindow_admin):
        MainWindow_admin.setObjectName("MainWindow_admin")
        MainWindow_admin.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_admin.sizePolicy().hasHeightForWidth())
        MainWindow_admin.setSizePolicy(sizePolicy)
        MainWindow_admin.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow_admin.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow_admin.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_admin)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_EVENT_CONTROL = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_EVENT_CONTROL.setGeometry(QtCore.QRect(90, 130, 270, 50))
        self.pushButton_EVENT_CONTROL.setStyleSheet("QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 2px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_EVENT_CONTROL.setObjectName("pushButton_EVENT_CONTROL")
        self.pushButton_PREFENCES_ADMIN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_PREFENCES_ADMIN.setGeometry(QtCore.QRect(90, 230, 270, 50))
        self.pushButton_PREFENCES_ADMIN.setStyleSheet("QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 2px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_PREFENCES_ADMIN.setObjectName("pushButton_PREFENCES_ADMIN")
        self.pushButton_SEND_MAIL = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_SEND_MAIL.setGeometry(QtCore.QRect(460, 130, 270, 50))
        self.pushButton_SEND_MAIL.setStyleSheet("QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 2px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_SEND_MAIL.setObjectName("pushButton_SEND_MAIL")
        self.pushButton_EXIT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_EXIT.setGeometry(QtCore.QRect(460, 230, 270, 50))
        self.pushButton_EXIT.setStyleSheet("QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 2px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_EXIT.setObjectName("pushButton_EXIT")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(90, 320, 641, 192))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 20, 291, 80))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(70, 20, 191, 41))
        self.label.setStyleSheet("font: 28pt \"Symbol\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 51, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("foto1.png"))
        self.label_2.setObjectName("label_2")
        MainWindow_admin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow_admin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_admin)
        self.statusbar.setObjectName("statusbar")
        MainWindow_admin.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_admin)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_admin)

    def retranslateUi(self, MainWindow_admin):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_admin.setWindowTitle(_translate("MainWindow_admin", "MainWindow"))
        self.pushButton_EVENT_CONTROL.setText(_translate("MainWindow_admin", "EVENT CONTROL"))
        self.pushButton_PREFENCES_ADMIN.setText(_translate("MainWindow_admin", "PREFENCES - ADMIN"))
        self.pushButton_SEND_MAIL.setText(_translate("MainWindow_admin", "SEND MAIL"))
        self.pushButton_EXIT.setText(_translate("MainWindow_admin", "EXIT"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_admin", "EVENT NAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_admin", "STARTING TIME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_admin", "USER E-MAIL"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_admin", "OWNER E-MAIL"))
        self.label.setText(_translate("MainWindow_admin", "ADMIN MENU"))
