# Form implementation generated from reading ui file 'admin_menu2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 799)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 850))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1600, 1000))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1200, 800))
        self.frame.setMaximumSize(QtCore.QSize(12000000, 8000000))
        self.frame.setStyleSheet("background-color:rgb(171, 186, 124)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(430, 250, 711, 441))
        self.tableWidget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(169)
        self.pushButton_2sendmail = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2sendmail.setGeometry(QtCore.QRect(60, 380, 171, 71))
        self.pushButton_2sendmail.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"}")
        self.pushButton_2sendmail.setObjectName("pushButton_2sendmail")
        self.pushButton_3exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3exit.setGeometry(QtCore.QRect(60, 510, 101, 51))
        self.pushButton_3exit.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"}")
        self.pushButton_3exit.setObjectName("pushButton_3exit")
        self.pushButton_4returnmenu = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4returnmenu.setGeometry(QtCore.QRect(60, 620, 281, 71))
        self.pushButton_4returnmenu.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 14px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"}")
        self.pushButton_4returnmenu.setObjectName("pushButton_4returnmenu")
        self.pushButtone1event = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtone1event.setGeometry(QtCore.QRect(60, 250, 211, 71))
        self.pushButtone1event.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"}")
        self.pushButtone1event.setObjectName("pushButtone1event")
        self.label1adminmenu = QtWidgets.QLabel(parent=self.frame)
        self.label1adminmenu.setGeometry(QtCore.QRect(480, 80, 221, 71))
        self.label1adminmenu.setStyleSheet("QLabel {\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    font-family: \"Comic Sans MS\";  /* Yazı tipi */\n"
"    font-size: 26px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 3px 3px 5px gray;  /* Gölge efekti */\n"
"}")
        self.label1adminmenu.setObjectName("label1adminmenu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Event Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Start Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Participant Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Organizer Email"))
        self.pushButton_2sendmail.setText(_translate("MainWindow", "SEND E-MAIL"))
        self.pushButton_3exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_4returnmenu.setText(_translate("MainWindow", "RETURN TO ADMIN PREFERENCE MENU"))
        self.pushButtone1event.setText(_translate("MainWindow", "EVENT REGISTRATION"))
        self.label1adminmenu.setText(_translate("MainWindow", "ADMIN MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
