# Form implementation generated from reading ui file 'AdminMenu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mwAdminMenu(object):
    def setupUi(self, mwAdminMenu):
        mwAdminMenu.setObjectName("mwAdminMenu")
        mwAdminMenu.resize(578, 609)
        self.centralwidget = QtWidgets.QWidget(parent=mwAdminMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 3, 571, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pbActionControl = QtWidgets.QPushButton(parent=self.frame)
        self.pbActionControl.setGeometry(QtCore.QRect(0, 3, 141, 31))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPrintPreview")
        self.pbActionControl.setIcon(icon)
        self.pbActionControl.setIconSize(QtCore.QSize(16, 16))
        self.pbActionControl.setObjectName("pbActionControl")
        self.pbSendMail = QtWidgets.QPushButton(parent=self.frame)
        self.pbSendMail.setGeometry(QtCore.QRect(140, 3, 141, 31))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentSend")
        self.pbSendMail.setIcon(icon)
        self.pbSendMail.setIconSize(QtCore.QSize(16, 16))
        self.pbSendMail.setObjectName("pbSendMail")
        self.pbPreferedAdmin = QtWidgets.QPushButton(parent=self.frame)
        self.pbPreferedAdmin.setGeometry(QtCore.QRect(280, 3, 141, 31))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::FolderOpen")
        self.pbPreferedAdmin.setIcon(icon)
        self.pbPreferedAdmin.setIconSize(QtCore.QSize(16, 16))
        self.pbPreferedAdmin.setObjectName("pbPreferedAdmin")
        self.pbExit = QtWidgets.QPushButton(parent=self.frame)
        self.pbExit.setGeometry(QtCore.QRect(420, 4, 141, 31))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::ApplicationExit")
        self.pbExit.setIcon(icon)
        self.pbExit.setIconSize(QtCore.QSize(12, 16))
        self.pbExit.setObjectName("pbExit")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 50, 571, 541))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(5, 1, 561, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        mwAdminMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mwAdminMenu)
        self.statusbar.setObjectName("statusbar")
        mwAdminMenu.setStatusBar(self.statusbar)

        self.retranslateUi(mwAdminMenu)
        QtCore.QMetaObject.connectSlotsByName(mwAdminMenu)

    def retranslateUi(self, mwAdminMenu):
        _translate = QtCore.QCoreApplication.translate
        mwAdminMenu.setWindowTitle(_translate("mwAdminMenu", "Admin Menu Window"))
        self.pbActionControl.setText(_translate("mwAdminMenu", "Action Control"))
        self.pbSendMail.setText(_translate("mwAdminMenu", "Send Mail"))
        self.pbPreferedAdmin.setText(_translate("mwAdminMenu", "Tercih - Admin Menu"))
        self.pbExit.setText(_translate("mwAdminMenu", "Exit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mwAdminMenu", "Action Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mwAdminMenu", "Start Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mwAdminMenu", "Participant Mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mwAdminMenu", "Organizer Mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwAdminMenu = QtWidgets.QMainWindow()
    ui = Ui_mwAdminMenu()
    ui.setupUi(mwAdminMenu)
    mwAdminMenu.show()
    sys.exit(app.exec())
