# Form implementation generated from reading ui file 'C:\Users\Admin\Downloads\VIT_PROJE\VIT_HOMEWORKS\WEEK7\Python-Module-Week7_Team1\applicationspage.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        Dialog.setStyleSheet("background-color:rgb(177, 194, 158)")
        self.pushButton_search = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_search.setGeometry(QtCore.QRect(340, 205, 81, 45))
        self.pushButton_search.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"QPushButton::hover{\n"
"color:white;\n"
"background:#47545a;\n"
"border-radius:10px;\n"
"font-weight:bold\n"
"}")
        self.pushButton_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_search.setIcon(icon)
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_defined = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_defined.setGeometry(QtCore.QRect(10, 90, 260, 45))
        self.pushButton_defined.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_defined.setObjectName("pushButton_defined")
        self.pushButton_unidentified = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_unidentified.setGeometry(QtCore.QRect(10, 140, 260, 45))
        self.pushButton_unidentified.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_unidentified.setObjectName("pushButton_unidentified")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_search.setGeometry(QtCore.QRect(10, 200, 321, 51))
        self.lineEdit_search.setStyleSheet("QLineEdit {\n"
"    font-size: 18px;\n"
"    font-family: Arial;\n"
"    color: #333;\n"
"    background-color: #fff;\n"
"    border: 4px solid #2c3e50;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);\n"
"}\n"
"QLineEdit:placeholder {\n"
"    color: rgba(150, 150, 150, 0.8);\n"
"    font-style: italic;\n"
"}\n"
"")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.pushButton_previous_control = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_previous_control.setGeometry(QtCore.QRect(290, 90, 260, 45))
        self.pushButton_previous_control.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_previous_control.setObjectName("pushButton_previous_control")
        self.pushButton_appfiltered = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_appfiltered.setGeometry(QtCore.QRect(290, 140, 260, 45))
        self.pushButton_appfiltered.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_appfiltered.setObjectName("pushButton_appfiltered")
        self.pushButton_dublicatereg = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_dublicatereg.setGeometry(QtCore.QRect(570, 90, 260, 45))
        self.pushButton_dublicatereg.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_dublicatereg.setObjectName("pushButton_dublicatereg")
        self.pushButton_differentreg = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_differentreg.setGeometry(QtCore.QRect(570, 140, 260, 45))
        self.pushButton_differentreg.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_differentreg.setObjectName("pushButton_differentreg")
        self.pushButton_preferences = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_preferences.setGeometry(QtCore.QRect(850, 90, 141, 91))
        self.pushButton_preferences.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_preferences.setObjectName("pushButton_preferences")
        self.pushButton_allapp = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_allapp.setGeometry(QtCore.QRect(520, 205, 191, 45))
        self.pushButton_allapp.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_allapp.setObjectName("pushButton_allapp")
        self.pushButton_exit = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(860, 205, 131, 45))
        self.pushButton_exit.setAutoFillBackground(False)
        self.pushButton_exit.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_mainmenu = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_mainmenu.setGeometry(QtCore.QRect(720, 205, 131, 45))
        self.pushButton_mainmenu.setAutoFillBackground(False)
        self.pushButton_mainmenu.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Hover sırasında daha belirgin gölge */\n"
"}")
        self.pushButton_mainmenu.setObjectName("pushButton_mainmenu")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 260, 981, 331))
        self.tableWidget.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"background-color: rgb(255, 243, 213);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 651, 51))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_defined.setText(_translate("Dialog", "Definied Mentor Interviews"))
        self.pushButton_unidentified.setText(_translate("Dialog", "Unidentified Mentor Interviews"))
        self.lineEdit_search.setText(_translate("Dialog", " Enter text to search!"))
        self.pushButton_previous_control.setText(_translate("Dialog", "VIT Previous Control"))
        self.pushButton_appfiltered.setText(_translate("Dialog", "Application Filtered"))
        self.pushButton_dublicatereg.setText(_translate("Dialog", "Duplicate Registered"))
        self.pushButton_differentreg.setText(_translate("Dialog", "Different Registered "))
        self.pushButton_preferences.setText(_translate("Dialog", "Preferences"))
        self.pushButton_allapp.setText(_translate("Dialog", "All Applications"))
        self.pushButton_exit.setText(_translate("Dialog", "EXIT"))
        self.pushButton_mainmenu.setText(_translate("Dialog", "MAIN MENU"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "History"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Phone"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "State"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Postal"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Current Status"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Economic Status"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">APPLICATIONS PAGE</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
