# Form implementation generated from reading ui file 'applications2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 850))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-40, -10, 1600, 1000))
        self.frame.setStyleSheet("background-color: rgb(202, 224, 188)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton1search = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton1search.setGeometry(QtCore.QRect(100, 110, 181, 41))
        self.pushButton1search.setStyleSheet("  font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #dcdcdc; /* Açık gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c0c0c0; /* Hover durumunda biraz daha koyu gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);")
        self.pushButton1search.setObjectName("pushButton1search")
        self.pushButton_2allapplications = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2allapplications.setGeometry(QtCore.QRect(100, 180, 221, 41))
        self.pushButton_2allapplications.setStyleSheet("\n"
"   font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_2allapplications.setObjectName("pushButton_2allapplications")
        self.pushButton_3vitcheck = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3vitcheck.setGeometry(QtCore.QRect(890, 240, 221, 41))
        self.pushButton_3vitcheck.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_3vitcheck.setObjectName("pushButton_3vitcheck")
        self.pushButton_4definedmentor = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4definedmentor.setGeometry(QtCore.QRect(350, 180, 221, 41))
        self.pushButton_4definedmentor.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_4definedmentor.setObjectName("pushButton_4definedmentor")
        self.pushButton_5endefined = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5endefined.setGeometry(QtCore.QRect(350, 250, 231, 41))
        self.pushButton_5endefined.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_5endefined.setObjectName("pushButton_5endefined")
        self.pushButton_6returnpremenu = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_6returnpremenu.setGeometry(QtCore.QRect(100, 250, 221, 41))
        self.pushButton_6returnpremenu.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_6returnpremenu.setObjectName("pushButton_6returnpremenu")
        self.pushButton_7duplicatereg = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_7duplicatereg.setGeometry(QtCore.QRect(620, 250, 221, 41))
        self.pushButton_7duplicatereg.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_7duplicatereg.setObjectName("pushButton_7duplicatereg")
        self.lineEdit1aramabosluk = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit1aramabosluk.setGeometry(QtCore.QRect(340, 110, 771, 41))
        self.lineEdit1aramabosluk.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit1aramabosluk.setStyleSheet("QLineEdit {\n"
"    color: #2c3e50; /* Yazı rengi */\n"
"    font-size: 16px; /* Yazı boyutu */\n"
"    font-family: Arial; /* Yazı tipi */\n"
"    border: 4px solid #2c3e50; /* Kalın çerçeve */\n"
"    border-radius: 10px; /* Köşeleri yuvarlatma */\n"
"    padding: 5px; /* İç boşluk */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.5); /* Yazı gölgesi */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5); /* Dış gölge */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(44, 62, 80, 0.5); /* Placeholder yazı rengi (daha belirgin) */\n"
"    font-style: italic; /* Yazıyı italik yap */\n"
"}")
        self.lineEdit1aramabosluk.setObjectName("lineEdit1aramabosluk")
        self.label2applications = QtWidgets.QLabel(parent=self.frame)
        self.label2applications.setGeometry(QtCore.QRect(350, 30, 471, 41))
        self.label2applications.setStyleSheet("   font-size: 26px;  /* Daha büyük yazı tipi */\n"
"    font-weight: bold; /* Kalın yazı tipi */\n"
"    font-family: \"Comic Sans MS\", sans-serif; /* Farklı bir yazı tipi */\n"
"    color: black;  /* Siyah renk */\n"
"    text-transform: uppercase; ")
        self.label2applications.setObjectName("label2applications")
        self.pushButton_8differentreg = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_8differentreg.setGeometry(QtCore.QRect(620, 180, 221, 41))
        self.pushButton_8differentreg.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_8differentreg.setObjectName("pushButton_8differentreg")
        self.pushButton_9appfilter = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_9appfilter.setGeometry(QtCore.QRect(890, 180, 221, 41))
        self.pushButton_9appfilter.setStyleSheet("  font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: white;\n"
"    background-color: #7f8c8d; /* Gri renk */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: none;\n"
"    \n"
"    /* Gölgelendirme eklemek için: */\n"
"    box-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3); /* Gölgenin boyutu ve rengi */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #95a5a6; /* Hover durumunda biraz daha açık gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5)")
        self.pushButton_9appfilter.setObjectName("pushButton_9appfilter")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget_2.setGeometry(QtCore.QRect(180, 320, 911, 391))
        self.tableWidget_2.setStyleSheet("background-color: rgba(255, 255, 255)")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(129)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1search.setText(_translate("MainWindow", "SEARCH"))
        self.pushButton_2allapplications.setText(_translate("MainWindow", "ALL APPLICATIONS"))
        self.pushButton_3vitcheck.setText(_translate("MainWindow", "PREVIOUS VIT CHECK"))
        self.pushButton_4definedmentor.setText(_translate("MainWindow", "DEFINED MENTOR MEETING"))
        self.pushButton_5endefined.setText(_translate("MainWindow", "UNDEFINED MENTOR MEETING"))
        self.pushButton_6returnpremenu.setText(_translate("MainWindow", "RETURN PREFERENCE MENU"))
        self.pushButton_7duplicatereg.setText(_translate("MainWindow", "DUPLICATE REGISTRATION "))
        self.lineEdit1aramabosluk.setPlaceholderText(_translate("MainWindow", "Enter the text you want to search for here"))
        self.label2applications.setText(_translate("MainWindow", "               APPLICATIONS"))
        self.pushButton_8differentreg.setText(_translate("MainWindow", "DIFFERENT REGISTRATION"))
        self.pushButton_9appfilter.setText(_translate("MainWindow", "APPLICATION FILTERING"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATE"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FULL NAME"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "E-MAIL"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PHONE NUMBER"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "POSTAL CODE"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PROVINCE"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", " CURRENT STATUS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
