# Form implementation generated from reading ui file 'basvurular.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(40, 40, 231, 41))
        self.pushButton_search.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 16pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_assigned = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_assigned.setGeometry(QtCore.QRect(40, 160, 231, 41))
        self.pushButton_assigned.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_assigned.setObjectName("pushButton_assigned")
        self.pushButton_unassigned = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_unassigned.setGeometry(QtCore.QRect(40, 220, 231, 41))
        self.pushButton_unassigned.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_unassigned.setObjectName("pushButton_unassigned")
        self.pushButton_previous_vit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_previous_vit.setGeometry(QtCore.QRect(40, 280, 231, 41))
        self.pushButton_previous_vit.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_previous_vit.setObjectName("pushButton_previous_vit")
        self.pushButton_duplicate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_duplicate.setGeometry(QtCore.QRect(40, 340, 231, 41))
        self.pushButton_duplicate.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_duplicate.setObjectName("pushButton_duplicate")
        self.pushButton_unique = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_unique.setGeometry(QtCore.QRect(40, 400, 231, 41))
        self.pushButton_unique.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_unique.setObjectName("pushButton_unique")
        self.pushButton_filter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_filter.setGeometry(QtCore.QRect(40, 460, 231, 41))
        self.pushButton_filter.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.pushButton_prefences = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_prefences.setGeometry(QtCore.QRect(290, 100, 281, 41))
        self.pushButton_prefences.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_prefences.setObjectName("pushButton_prefences")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(590, 100, 181, 41))
        self.pushButton_exit.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_all_app = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_all_app.setGeometry(QtCore.QRect(40, 100, 231, 41))
        self.pushButton_all_app.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 20pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 1px; /* Köşe yuvarlama */\n"
"    padding: 1px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_all_app.setObjectName("pushButton_all_app")
        self.lineEdit_basvurular = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_basvurular.setGeometry(QtCore.QRect(290, 40, 481, 41))
        self.lineEdit_basvurular.setObjectName("lineEdit_basvurular")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(290, 160, 481, 351))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(63)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(19)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_search.setText(_translate("MainWindow", "SEARCH"))
        self.pushButton_assigned.setText(_translate("MainWindow", "Assigned Mentor Meetings "))
        self.pushButton_unassigned.setText(_translate("MainWindow", "Unassigned Mentor Meetings"))
        self.pushButton_previous_vit.setText(_translate("MainWindow", "Previous VIT Check"))
        self.pushButton_duplicate.setText(_translate("MainWindow", "Duplicate Records"))
        self.pushButton_unique.setText(_translate("MainWindow", "Unique Records "))
        self.pushButton_filter.setText(_translate("MainWindow", "Filter Applications"))
        self.pushButton_prefences.setText(_translate("MainWindow", "Return to Preferences Screen"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_all_app.setText(_translate("MainWindow", "All Applications"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Posta Code"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Current Status"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Economic Status"))
