# Form implementation generated from reading ui file 'interviews.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_interviews(object):
    def setupUi(self, interviews):
        interviews.setObjectName("interviews")
        interviews.resize(885, 605)
        self.mulakatlarFRAME = QtWidgets.QFrame(parent=interviews)
        self.mulakatlarFRAME.setGeometry(QtCore.QRect(20, 60, 821, 451))
        self.mulakatlarFRAME.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mulakatlarFRAME.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mulakatlarFRAME.setObjectName("mulakatlarFRAME")
        self.pb_search = QtWidgets.QPushButton(parent=self.mulakatlarFRAME)
        self.pb_search.setGeometry(QtCore.QRect(700, 90, 93, 31))
        self.pb_search.setObjectName("pb_search")
        self.pb_submittedProjects = QtWidgets.QPushButton(parent=self.mulakatlarFRAME)
        self.pb_submittedProjects.setGeometry(QtCore.QRect(50, 130, 331, 41))
        self.pb_submittedProjects.setObjectName("pb_submittedProjects")
        self.pb_exit = QtWidgets.QPushButton(parent=self.mulakatlarFRAME)
        self.pb_exit.setGeometry(QtCore.QRect(710, 420, 93, 28))
        self.pb_exit.setObjectName("pb_exit")
        self.pb_incomingprojects = QtWidgets.QPushButton(parent=self.mulakatlarFRAME)
        self.pb_incomingprojects.setGeometry(QtCore.QRect(440, 130, 361, 41))
        self.pb_incomingprojects.setObjectName("pb_incomingprojects")
        self.le_search = QtWidgets.QLineEdit(parent=self.mulakatlarFRAME)
        self.le_search.setGeometry(QtCore.QRect(50, 90, 641, 31))
        self.le_search.setText("")
        self.le_search.setObjectName("le_search")
        self.tw_interviews = QtWidgets.QTableWidget(parent=self.mulakatlarFRAME)
        self.tw_interviews.setGeometry(QtCore.QRect(50, 200, 751, 192))
        self.tw_interviews.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tw_interviews.setAutoFillBackground(False)
        self.tw_interviews.setObjectName("tw_interviews")
        self.tw_interviews.setColumnCount(3)
        self.tw_interviews.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tw_interviews.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tw_interviews.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tw_interviews.setHorizontalHeaderItem(2, item)
        self.tw_interviews.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_interviews.horizontalHeader().setDefaultSectionSize(253)
        self.pb_returnPreferences = QtWidgets.QPushButton(parent=self.mulakatlarFRAME)
        self.pb_returnPreferences.setGeometry(QtCore.QRect(50, 420, 391, 31))
        self.pb_returnPreferences.setObjectName("pb_returnPreferences")
        self.l_interviews = QtWidgets.QLabel(parent=self.mulakatlarFRAME)
        self.l_interviews.setGeometry(QtCore.QRect(290, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.l_interviews.setFont(font)
        self.l_interviews.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.l_interviews.setObjectName("l_interviews")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.mulakatlarFRAME)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 20, 751, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(interviews)
        QtCore.QMetaObject.connectSlotsByName(interviews)

    def retranslateUi(self, interviews):
        _translate = QtCore.QCoreApplication.translate
        interviews.setWindowTitle(_translate("interviews", "Dialog"))
        self.pb_search.setText(_translate("interviews", "Search"))
        self.pb_submittedProjects.setText(_translate("interviews", "submitted projects"))
        self.pb_exit.setText(_translate("interviews", "EXIT"))
        self.pb_incomingprojects.setText(_translate("interviews", "incoming projects"))
        self.le_search.setPlaceholderText(_translate("interviews", "Enter the text to search "))
        item = self.tw_interviews.horizontalHeaderItem(0)
        item.setText(_translate("interviews", "Name- Surname"))
        item = self.tw_interviews.horizontalHeaderItem(1)
        item.setText(_translate("interviews", "Project Delivery Time"))
        item = self.tw_interviews.horizontalHeaderItem(2)
        item.setText(_translate("interviews", "Project Arrival Time"))
        self.pb_returnPreferences.setText(_translate("interviews", "Return to preferences screen"))
        self.l_interviews.setText(_translate("interviews", "INTERVIEWS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interviews = QtWidgets.QDialog()
    ui = Ui_interviews()
    ui.setupUi(interviews)
    interviews.show()
    sys.exit(app.exec())
