# Form implementation generated from reading ui file 'login_window22.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 770)
        MainWindow.setMinimumSize(QtCore.QSize(650, 720))
        MainWindow.setMaximumSize(QtCore.QSize(750, 820))
        MainWindow.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 1000, 1000))
        self.frame.setStyleSheet("background-color:rgb(252, 231, 200)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton1login = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton1login.setGeometry(QtCore.QRect(310, 370, 121, 31))
        self.pushButton1login.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"}\n"
"")
        self.pushButton1login.setObjectName("pushButton1login")
        self.pushButton_2exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2exit.setGeometry(QtCore.QRect(310, 440, 121, 31))
        self.pushButton_2exit.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"}\n"
"")
        self.pushButton_2exit.setObjectName("pushButton_2exit")
        self.label1username = QtWidgets.QLabel(parent=self.frame)
        self.label1username.setGeometry(QtCore.QRect(110, 190, 121, 31))
        self.label1username.setStyleSheet("font-family: \"Comic Sans MS\";  /* Yazı tipi */\n"
"    font-size: 20px;  /* Yazı boyutu */\n"
"  ")
        self.label1username.setObjectName("label1username")
        self.label_2password = QtWidgets.QLabel(parent=self.frame)
        self.label_2password.setGeometry(QtCore.QRect(110, 280, 131, 31))
        self.label_2password.setStyleSheet("font-family: \"Comic Sans MS\";  /* Yazı tipi */\n"
"    font-size: 20px;  /* Yazı boyutu */\n"
"    ")
        self.label_2password.setObjectName("label_2password")
        self.label_3crm = QtWidgets.QLabel(parent=self.frame)
        self.label_3crm.setGeometry(QtCore.QRect(320, 80, 141, 41))
        self.label_3crm.setStyleSheet("font: 63 28pt \"Bahnschrift SemiBold Condensed\";")
        self.label_3crm.setObjectName("label_3crm")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(260, 190, 211, 41))
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit.setStyleSheet("\n"
"background-color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 280, 211, 41))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1login.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_2exit.setText(_translate("MainWindow", "EXIT"))
        self.label1username.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">USERNAME</span></p></body></html>"))
        self.label1username.setText(_translate("MainWindow", "USERNAME"))
        self.label_2password.setText(_translate("MainWindow", "PASSWORD"))
        self.label_3crm.setText(_translate("MainWindow", "CRM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
