# Form implementation generated from reading ui file 'Mentor.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mentor(object):
    def setupUi(self, Mentor):
        Mentor.setObjectName("Mentor")
        Mentor.resize(857, 682)
        Mentor.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(parent=Mentor)
        self.centralwidget.setObjectName("centralwidget")
        self.GBox_Mentor = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.GBox_Mentor.setGeometry(QtCore.QRect(30, 10, 761, 561))
        self.GBox_Mentor.setObjectName("GBox_Mentor")
        self.PB_Mentor_Find = QtWidgets.QPushButton(parent=self.GBox_Mentor)
        self.PB_Mentor_Find.setGeometry(QtCore.QRect(260, 80, 101, 41))
        self.PB_Mentor_Find.setObjectName("PB_Mentor_Find")
        self.Mentor_Label = QtWidgets.QLabel(parent=self.GBox_Mentor)
        self.Mentor_Label.setGeometry(QtCore.QRect(340, 30, 101, 41))
        self.Mentor_Label.setObjectName("Mentor_Label")
        self.comboBox_Mentor = QtWidgets.QComboBox(parent=self.GBox_Mentor)
        self.comboBox_Mentor.setGeometry(QtCore.QRect(360, 150, 371, 41))
        self.comboBox_Mentor.setObjectName("comboBox_Mentor")
        self.comboBox_Mentor.addItem("")
        self.comboBox_Mentor.addItem("")
        self.TBrowser_Mentor_name_surname = QtWidgets.QTextBrowser(parent=self.GBox_Mentor)
        self.TBrowser_Mentor_name_surname.setGeometry(QtCore.QRect(380, 80, 351, 41))
        self.TBrowser_Mentor_name_surname.setObjectName("TBrowser_Mentor_name_surname")
        self.Tabwidget_mentor_interviewdetails = QtWidgets.QTabWidget(parent=self.GBox_Mentor)
        self.Tabwidget_mentor_interviewdetails.setGeometry(QtCore.QRect(40, 220, 641, 301))
        self.Tabwidget_mentor_interviewdetails.setIconSize(QtCore.QSize(50, 16))
        self.Tabwidget_mentor_interviewdetails.setMovable(True)
        self.Tabwidget_mentor_interviewdetails.setObjectName("Tabwidget_mentor_interviewdetails")
        self.Tab_mentor_int_date = QtWidgets.QWidget()
        self.Tab_mentor_int_date.setObjectName("Tab_mentor_int_date")
        self.Tabwidget_mentor_interviewdetails.addTab(self.Tab_mentor_int_date, "")
        self.Tab_mentor_name = QtWidgets.QWidget()
        self.Tab_mentor_name.setObjectName("Tab_mentor_name")
        self.Tabwidget_mentor_interviewdetails.addTab(self.Tab_mentor_name, "")
        self.Tab_mentor_mentor = QtWidgets.QWidget()
        self.Tab_mentor_mentor.setObjectName("Tab_mentor_mentor")
        self.Tabwidget_mentor_interviewdetails.addTab(self.Tab_mentor_mentor, "")
        self.Tab_mentor_IT_knowledge = QtWidgets.QWidget()
        self.Tab_mentor_IT_knowledge.setObjectName("Tab_mentor_IT_knowledge")
        self.Tabwidget_mentor_interviewdetails.addTab(self.Tab_mentor_IT_knowledge, "")
        self.Tab_mentor_intensity = QtWidgets.QWidget()
        self.Tab_mentor_intensity.setObjectName("Tab_mentor_intensity")
        self.Tabwidget_mentor_interviewdetails.addTab(self.Tab_mentor_intensity, "")
        self.Tab_mentor_comments = QtWidgets.QWidget()
        self.Tab_mentor_comments.setObjectName("Tab_mentor_comments")
        self.Tabwidget_mentor_interviewdetails.addTab(self.Tab_mentor_comments, "")
        self.PB_mentor_preferences = QtWidgets.QPushButton(parent=self.GBox_Mentor)
        self.PB_mentor_preferences.setGeometry(QtCore.QRect(20, 150, 91, 31))
        self.PB_mentor_preferences.setObjectName("PB_mentor_preferences")
        self.PB_mentor_exit = QtWidgets.QPushButton(parent=self.GBox_Mentor)
        self.PB_mentor_exit.setGeometry(QtCore.QRect(174, 153, 81, 31))
        self.PB_mentor_exit.setObjectName("PB_mentor_exit")
        self.PB_mentor_all_interviews = QtWidgets.QPushButton(parent=self.GBox_Mentor)
        self.PB_mentor_all_interviews.setGeometry(QtCore.QRect(30, 83, 201, 31))
        self.PB_mentor_all_interviews.setObjectName("PB_mentor_all_interviews")
        Mentor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Mentor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 22))
        self.menubar.setObjectName("menubar")
        Mentor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Mentor)
        self.statusbar.setObjectName("statusbar")
        Mentor.setStatusBar(self.statusbar)

        self.retranslateUi(Mentor)
        self.Tabwidget_mentor_interviewdetails.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Mentor)

    def retranslateUi(self, Mentor):
        _translate = QtCore.QCoreApplication.translate
        Mentor.setWindowTitle(_translate("Mentor", "MainWindow"))
        self.GBox_Mentor.setTitle(_translate("Mentor", "GroupBox_mentor"))
        self.PB_Mentor_Find.setText(_translate("Mentor", "Find"))
        self.Mentor_Label.setText(_translate("Mentor", "MENTOR MENU"))
        self.comboBox_Mentor.setItemText(0, _translate("Mentor", "   Appropriate to participate in the entire VIT project"))
        self.comboBox_Mentor.setItemText(1, _translate("Mentor", "   Appropriate to the first part of IT Education"))
        self.Tabwidget_mentor_interviewdetails.setTabText(self.Tabwidget_mentor_interviewdetails.indexOf(self.Tab_mentor_int_date), _translate("Mentor", "Interview date"))
        self.Tabwidget_mentor_interviewdetails.setTabText(self.Tabwidget_mentor_interviewdetails.indexOf(self.Tab_mentor_name), _translate("Mentor", "Name Surname"))
        self.Tabwidget_mentor_interviewdetails.setTabText(self.Tabwidget_mentor_interviewdetails.indexOf(self.Tab_mentor_mentor), _translate("Mentor", "Mentor"))
        self.Tabwidget_mentor_interviewdetails.setTabText(self.Tabwidget_mentor_interviewdetails.indexOf(self.Tab_mentor_IT_knowledge), _translate("Mentor", "IT Knowledge"))
        self.Tabwidget_mentor_interviewdetails.setTabText(self.Tabwidget_mentor_interviewdetails.indexOf(self.Tab_mentor_intensity), _translate("Mentor", "intensity"))
        self.Tabwidget_mentor_interviewdetails.setTabText(self.Tabwidget_mentor_interviewdetails.indexOf(self.Tab_mentor_comments), _translate("Mentor", "Comments"))
        self.PB_mentor_preferences.setText(_translate("Mentor", "Preferences"))
        self.PB_mentor_exit.setText(_translate("Mentor", "Exit"))
        self.PB_mentor_all_interviews.setText(_translate("Mentor", "All Interviews"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mentor = QtWidgets.QMainWindow()
    ui = Ui_Mentor()
    ui.setupUi(Mentor)
    Mentor.show()
    sys.exit(app.exec())
