# Form implementation generated from reading ui file 'preference_menu2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 770)
        MainWindow.setMinimumSize(QtCore.QSize(650, 720))
        MainWindow.setMaximumSize(QtCore.QSize(750, 820))
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-30, -10, 1000, 1000))
        self.frame.setStyleSheet("background-color:rgb(177, 194, 158)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButtonapplications = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonapplications.setGeometry(QtCore.QRect(90, 180, 201, 61))
        self.pushButtonapplications.setStyleSheet(" background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"")
        self.pushButtonapplications.setObjectName("pushButtonapplications")
        self.pushButton_2mentormeeting = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2mentormeeting.setGeometry(QtCore.QRect(400, 180, 201, 61))
        self.pushButton_2mentormeeting.setStyleSheet("  background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"")
        self.pushButton_2mentormeeting.setObjectName("pushButton_2mentormeeting")
        self.pushButton_5returnmainmenu = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5returnmainmenu.setGeometry(QtCore.QRect(400, 490, 201, 61))
        self.pushButton_5returnmainmenu.setStyleSheet("  background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"")
        self.pushButton_5returnmainmenu.setObjectName("pushButton_5returnmainmenu")
        self.pushButton_3interviews = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3interviews.setGeometry(QtCore.QRect(250, 330, 201, 61))
        self.pushButton_3interviews.setStyleSheet("  background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"")
        self.pushButton_3interviews.setObjectName("pushButton_3interviews")
        self.pushButton_4exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4exit.setGeometry(QtCore.QRect(90, 490, 201, 61))
        self.pushButton_4exit.setStyleSheet("  background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"")
        self.pushButton_4exit.setObjectName("pushButton_4exit")
        self.labelpremenu = QtWidgets.QLabel(parent=self.frame)
        self.labelpremenu.setGeometry(QtCore.QRect(220, 60, 281, 51))
        self.labelpremenu.setStyleSheet("QLabel {\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    font-family: \"Comic Sans MS\";  /* Yazı tipi */\n"
"    font-size: 24px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 3px 3px 5px gray;  /* Gölge efekti */\n"
"}\n"
"")
        self.labelpremenu.setObjectName("labelpremenu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonapplications.setText(_translate("MainWindow", "APPLICATIONS"))
        self.pushButton_2mentormeeting.setText(_translate("MainWindow", "MENTOR MEETING"))
        self.pushButton_5returnmainmenu.setText(_translate("MainWindow", "RETURN MAIN MENU"))
        self.pushButton_3interviews.setText(_translate("MainWindow", "INTERVIEWS"))
        self.pushButton_4exit.setText(_translate("MainWindow", "EXIT"))
        self.labelpremenu.setText(_translate("MainWindow", "PREFERENCE MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
