# Form implementation generated from reading ui file 'prefences.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background: rgb(235, 235, 235);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Symbol")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 28pt \"Symbol\";")
        self.label.setObjectName("label")
        self.pushButton_applications = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_applications.setGeometry(QtCore.QRect(180, 180, 171, 40))
        self.pushButton_applications.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 2px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}")
        self.pushButton_applications.setObjectName("pushButton_applications")
        self.pushButton_mentor_interview = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_mentor_interview.setGeometry(QtCore.QRect(450, 180, 171, 40))
        self.pushButton_mentor_interview.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 2px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}")
        self.pushButton_mentor_interview.setObjectName("pushButton_mentor_interview")
        self.pushButton_interviews = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_interviews.setGeometry(QtCore.QRect(180, 270, 171, 40))
        self.pushButton_interviews.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 2px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}")
        self.pushButton_interviews.setObjectName("pushButton_interviews")
        self.pushButton_prefences_main_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_prefences_main_menu.setGeometry(QtCore.QRect(450, 270, 171, 40))
        self.pushButton_prefences_main_menu.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 2px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}")
        self.pushButton_prefences_main_menu.setObjectName("pushButton_prefences_main_menu")
        self.pushButton_prefences_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_prefences_exit.setGeometry(QtCore.QRect(180, 360, 441, 40))
        self.pushButton_prefences_exit.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: 14pt \"Symbol\";\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background: rgba(0, 84, 147, 128);\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 2px; /* Küçük padding */\n"
"    border: 1px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(145, 145, 145); \n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"}\n"
"")
        self.pushButton_prefences_exit.setObjectName("pushButton_prefences_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PREFENCES"))
        self.pushButton_applications.setText(_translate("MainWindow", "APPLICATIONS"))
        self.pushButton_mentor_interview.setText(_translate("MainWindow", "MENTOR INTERVIEW"))
        self.pushButton_interviews.setText(_translate("MainWindow", "INTERVIEWS"))
        self.pushButton_prefences_main_menu.setText(_translate("MainWindow", "MAIN MENU"))
        self.pushButton_prefences_exit.setText(_translate("MainWindow", "EXIT"))
