# Form implementation generated from reading ui file 'preference_admin_menu2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 770)
        MainWindow.setMinimumSize(QtCore.QSize(650, 720))
        MainWindow.setMaximumSize(QtCore.QSize(750, 820))
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 900, 1000))
        self.frame.setStyleSheet("background-color:rgb(250, 218, 122)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton1applications = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton1applications.setGeometry(QtCore.QRect(100, 170, 171, 51))
        self.pushButton1applications.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);  /* Gölgeleme efekti ekledik */\n"
"}\n"
"")
        self.pushButton1applications.setObjectName("pushButton1applications")
        self.pushButton_2mentormeeting = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2mentormeeting.setGeometry(QtCore.QRect(410, 170, 181, 51))
        self.pushButton_2mentormeeting.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);  /* Gölgeleme efekti ekledik */\n"
"}\n"
"")
        self.pushButton_2mentormeeting.setObjectName("pushButton_2mentormeeting")
        self.pushButton_5returmainmenu = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5returmainmenu.setGeometry(QtCore.QRect(410, 510, 191, 51))
        self.pushButton_5returmainmenu.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);  /* Gölgeleme efekti ekledik */\n"
"}\n"
"")
        self.pushButton_5returmainmenu.setObjectName("pushButton_5returmainmenu")
        self.pushButton_3interviews = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3interviews.setGeometry(QtCore.QRect(250, 290, 191, 51))
        self.pushButton_3interviews.setStyleSheet(" QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);  /* Gölgeleme efekti ekledik */\n"
"}\n"
"")
        self.pushButton_3interviews.setObjectName("pushButton_3interviews")
        self.pushButton_4exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4exit.setGeometry(QtCore.QRect(100, 510, 171, 51))
        self.pushButton_4exit.setStyleSheet(" QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);  /* Gölgeleme efekti ekledik */\n"
"}\n"
"")
        self.pushButton_4exit.setObjectName("pushButton_4exit")
        self.labelbaslikpreadmin = QtWidgets.QLabel(parent=self.frame)
        self.labelbaslikpreadmin.setGeometry(QtCore.QRect(160, 30, 361, 51))
        self.labelbaslikpreadmin.setStyleSheet("QLabel {\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    font-family: \"Comic Sans MS\";  /* Yazı tipi */\n"
"    font-size: 26px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 3px 3px 5px gray;  /* Gölge efekti */\n"
"}\n"
"")
        self.labelbaslikpreadmin.setObjectName("labelbaslikpreadmin")
        self.pushButton_6adminmenu = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_6adminmenu.setGeometry(QtCore.QRect(250, 390, 191, 51))
        self.pushButton_6adminmenu.setStyleSheet("QPushButton {\n"
"    background-color: #D3D3D3;  /* Açık gri arka plan */\n"
"    color: black;  /* Yazı rengi siyah */\n"
"    border: 2px solid black;  /* İnce siyah kenar çerçevesi */\n"
"    border-radius: 5px;  /* Yuvarlak köşeler (isteğe bağlı) */\n"
"    font-family: \"Arial\";  /* Yazı tipi */\n"
"    font-size: 16px;  /* Yazı boyutu */\n"
"    font-weight: bold;  /* Kalın yazı tipi */\n"
"    text-shadow: 1px 1px 3px gray;  /* Gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A9A9A9;  /* Butona hover yapıldığında arka plan rengi değişir */\n"
"    border: 2px solid #333;  /* Hover durumunda kenar çerçevesi koyulaşır */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);  /* Gölgeleme efekti ekledik */\n"
"}\n"
"")
        self.pushButton_6adminmenu.setObjectName("pushButton_6adminmenu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1applications.setText(_translate("MainWindow", "APPLICATIONS"))
        self.pushButton_2mentormeeting.setText(_translate("MainWindow", "MENTOR MEETING"))
        self.pushButton_5returmainmenu.setText(_translate("MainWindow", "RETURN MAIN MENU"))
        self.pushButton_3interviews.setText(_translate("MainWindow", "INTERVIEWS"))
        self.pushButton_4exit.setText(_translate("MainWindow", "EXIT"))
        self.labelbaslikpreadmin.setText(_translate("MainWindow", "PREFERENCE ADMIN MENU"))
        self.pushButton_6adminmenu.setText(_translate("MainWindow", "ADMIN MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
