# Form implementation generated from reading ui file 'pre_usermenu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1000, 600))
        Dialog.setMaximumSize(QtCore.QSize(1000, 600))
        Dialog.setStyleSheet("background-color:rgb(177, 194, 158)")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(175, 50, 651, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_applications = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_applications.setGeometry(QtCore.QRect(640, 210, 251, 51))
        self.pushButton_applications.setAutoFillBackground(False)
        self.pushButton_applications.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_applications.setObjectName("pushButton_applications")
        self.pushButton_interview = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_interview.setGeometry(QtCore.QRect(370, 330, 251, 51))
        self.pushButton_interview.setAutoFillBackground(False)
        self.pushButton_interview.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_interview.setObjectName("pushButton_interview")
        self.pushButton_exit = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(840, 520, 141, 61))
        self.pushButton_exit.setAutoFillBackground(False)
        self.pushButton_exit.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_mentor = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_mentor.setGeometry(QtCore.QRect(100, 210, 251, 51))
        self.pushButton_mentor.setAutoFillBackground(False)
        self.pushButton_mentor.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_mentor.setObjectName("pushButton_mentor")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">PREFERENCE -USER MENU</span></p></body></html>"))
        self.pushButton_applications.setText(_translate("Dialog", "APPLICATIONS"))
        self.pushButton_interview.setText(_translate("Dialog", "INTERVIEWS"))
        self.pushButton_exit.setText(_translate("Dialog", "EXIT"))
        self.pushButton_mentor.setText(_translate("Dialog", "MENTOR INTERVIEW"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
