# Form implementation generated from reading ui file 'pre_usermenu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1000, 600))
        Dialog.setMaximumSize(QtCore.QSize(1000, 600))
        Dialog.setStyleSheet("background-color:rgb(177, 194, 158)")
        self.pushButton_applications = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_applications.setGeometry(QtCore.QRect(640, 210, 251, 51))
        self.pushButton_applications.setAutoFillBackground(False)
        self.pushButton_applications.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_applications.setObjectName("pushButton_applications")
        self.pushButton_interview = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_interview.setGeometry(QtCore.QRect(370, 330, 251, 51))
        self.pushButton_interview.setAutoFillBackground(False)
        self.pushButton_interview.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_interview.setObjectName("pushButton_interview")
        self.pushButton_exit = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(840, 520, 141, 61))
        self.pushButton_exit.setAutoFillBackground(False)
        self.pushButton_exit.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_mentor = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_mentor.setGeometry(QtCore.QRect(100, 210, 251, 51))
        self.pushButton_mentor.setAutoFillBackground(False)
        self.pushButton_mentor.setStyleSheet("\n"
"QPushButton {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"    color: black; /* Siyah yazı rengi */\n"
"    background-color: #d3d3a1; /* Sarıya yakın gri arka plan rengi */\n"
"    border-radius: 8px; /* Köşe yuvarlama */\n"
"    padding: 8px; /* Küçük padding */\n"
"    border: 2px solid black; /* İnce siyah çerçeve */\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b0b072; /* Hover durumunda daha koyu sarımsı gri */\n"
"    /* Hover durumunda gölgeyi değiştirmek için */\n"
"\n"
"}")
        self.pushButton_mentor.setObjectName("pushButton_mentor")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(180, 50, 641, 61))
        self.label_5.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"color: rgb(0, 100, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_applications.setText(_translate("Dialog", "APPLICATIONS"))
        self.pushButton_interview.setText(_translate("Dialog", "INTERVIEWS"))
        self.pushButton_exit.setText(_translate("Dialog", "EXIT"))
        self.pushButton_mentor.setText(_translate("Dialog", "MENTOR INTERVIEW"))
        self.label_5.setText(_translate("Dialog", "PREFERENCE -USER MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
